# Generated by Django 4.2.8 on 2026-04-20 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Cardiology", "Cardiology"),
                            ("Neurology", "Neurology"),
                            ("Orthopedics", "Orthopedics"),
                            ("Pediatrics", "Pediatrics"),
                            ("Gynecology", "Gynecology"),
                            ("General Medicine", "General Medicine"),
                            ("Emergency", "Emergency"),
                            ("Oncology", "Oncology"),
                            ("Dermatology", "Dermatology"),
                            ("ENT", "ENT"),
                            ("Ophthalmology", "Ophthalmology"),
                            ("Psychiatry", "Psychiatry"),
                            ("Urology", "Urology"),
                            ("Gastroenterology", "Gastroenterology"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("Shivajinagar", "Shivajinagar"),
                            ("Kothrud", "Kothrud"),
                            ("Hadapsar", "Hadapsar"),
                            ("Pimpri-Chinchwad", "Pimpri-Chinchwad"),
                            ("Wakad", "Wakad"),
                            ("Baner", "Baner"),
                            ("Aundh", "Aundh"),
                            ("Viman Nagar", "Viman Nagar"),
                            ("Koregaon Park", "Koregaon Park"),
                            ("Deccan", "Deccan"),
                            ("Kalyani Nagar", "Kalyani Nagar"),
                            ("Magarpatta", "Magarpatta"),
                            ("Swargate", "Swargate"),
                            ("Camp", "Camp"),
                            ("Nigdi", "Nigdi"),
                        ],
                        max_length=100,
                    ),
                ),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="hospital_photos/"
                    ),
                ),
                ("total_beds", models.PositiveIntegerField(default=0)),
                ("available_beds", models.PositiveIntegerField(default=0)),
                ("icu_beds", models.PositiveIntegerField(default=0)),
                ("available_icu_beds", models.PositiveIntegerField(default=0)),
                ("emergency", models.BooleanField(default=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
                ),
                (
                    "established_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("qualification", models.CharField(blank=True, max_length=200)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("available_days", models.CharField(default="Mon-Sat", max_length=200)),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=8),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="core.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="core.hospital",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="core.hospital",
            ),
        ),
        migrations.CreateModel(
            name="BedBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("patient_name", models.CharField(max_length=200)),
                ("patient_age", models.PositiveIntegerField()),
                (
                    "patient_gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("patient_phone", models.CharField(max_length=15)),
                ("patient_email", models.EmailField(blank=True, max_length=254)),
                ("patient_address", models.TextField()),
                ("aadhar_number", models.CharField(blank=True, max_length=12)),
                ("medical_condition", models.TextField()),
                (
                    "bed_type",
                    models.CharField(
                        choices=[
                            ("General", "General Ward"),
                            ("Semi-Private", "Semi-Private"),
                            ("Private", "Private Room"),
                            ("ICU", "ICU"),
                            ("NICU", "NICU"),
                        ],
                        default="General",
                        max_length=20,
                    ),
                ),
                ("admission_date", models.DateField()),
                ("expected_days", models.PositiveIntegerField(default=1)),
                ("services_required", models.TextField(blank=True)),
                ("emergency_contact_name", models.CharField(max_length=200)),
                ("emergency_contact_phone", models.CharField(max_length=15)),
                ("emergency_contact_relation", models.CharField(max_length=50)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UPI", "UPI / GPay / PhonePe"),
                            ("Card", "Credit / Debit Card"),
                            ("NetBanking", "Net Banking"),
                            ("Cash", "Cash at Counter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
                ),
                ("payment_status", models.CharField(default="Paid", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Cancelled", "Cancelled"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bed_bookings",
                        to="core.hospital",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bed_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("patient_name", models.CharField(max_length=200)),
                ("patient_age", models.PositiveIntegerField()),
                (
                    "patient_gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("patient_phone", models.CharField(max_length=15)),
                ("patient_email", models.EmailField(blank=True, max_length=254)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                ("reason_for_visit", models.TextField()),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UPI", "UPI / GPay / PhonePe"),
                            ("Card", "Credit / Debit Card"),
                            ("NetBanking", "Net Banking"),
                            ("Cash", "Cash at Counter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=300.0, max_digits=10),
                ),
                ("payment_status", models.CharField(default="Paid", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Cancelled", "Cancelled"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.department",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="core.hospital",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("hospital", "name")},
        ),
    ]
