# Generated by Django 4.2.8 on 2026-04-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="lat",
            field=models.FloatField(default=18.5204),
        ),
        migrations.AddField(
            model_name="hospital",
            name="lng",
            field=models.FloatField(default=73.8567),
        ),
    ]
