# Generated by Django 4.2.8 on 2026-04-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_hospital_lat_hospital_lng"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="lng",
        ),
        migrations.AddField(
            model_name="hospital",
            name="image_url",
            field=models.URLField(blank=True, help_text="External image URL fallback"),
        ),
        migrations.AddField(
            model_name="hospital",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
